name: pr-deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
        shell: bash

      - name: checkout base repo
        uses: actions/checkout@v2
        with:
          path: deploy

      - name: checkout preview repo
        uses: actions/checkout@v2
        with:
          repository: felixoi/pr-preview
          path: preview
          ref: gh-pages
          persist-credentials: false

      - name: test action
        uses: felixoi/pr-preview-action@v0.4.18
        with:
          PREVIEW_REPOSITORY: "felixoi/pr-preview"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PA_TOKEN: "${{ secrets.PA_TOKEN }}"
          PULL_REQUEST_ID: "${{ env.PULL_NUMBER }}"
